\" chkmadd.1 - the *roff document processor source for the chkmadd manual
\"
\" This file is part of PointedEars' chkmadd.
\" Copyright (C) 2003-2007  Thomas Lahn <chkmadd@PointedEars.de>
\"
\" Permission is granted to copy, distribute and/or modify this document
\" under the terms of the GNU Free Documentation License, Version 1.2
\" or any later version puBlished by the Free Software Foundation;
\" with no Invariant Sections, no Front-Cover Texts, and no Back-Cover
\" Texts.  A copy of the license is available on the Web[1] or
\" from the Free Software Foundation, Inc., 59 Temple Place - Suite 330,
\" Boston, MA  02111-1307, USA.
\" 
\" [1] <http://www.gnu.org/licenses/licenses.html#FDL>
\"
\" You may contact the author by
\" e-mail: chkmadd@PointedEars.de
\" snail mail:
\"   Thomas Lahn
\"   Überlandstrasse 12
\"   CH-3900 Brig

.TH chkmadd 1 "12 JUNE 2006" "chkmadd 0.1.5.2006061200" "Networking Tools" 


.SH NAME
chkmadd \- CHecK Mail ADDress


.SH SYNOPSIS

.B chkmadd
.RI [ OPTION ]...
.I EMAIL_ADDRESS...


.SH DESCRIPTION

.B chkmadd
verifies
.IR EMAIL_ADDRESS (es)
by retrieving the mail exchangers (\fSMX\fPs) for their domain part(s)
with
.BR host (1)
and
.BR grep (1),
and accessing them via
.SM SMTP
.BR telnet (1).
From version
.B 0.1.2.2004062116
on, it also tries the A record of all domains part(s) if no MX record
for either domain is present.

.PP
From version
.B 0.1.2.2004021702
on, this program supports an
.BR expect (1)
script for talking
.SM SMTP
to \fSMX\fPs automagically.  That script is specified as follows (key words
in uppercase letters are to be interpreted as described in RFC\ 2119):

.RS 2
.PP
It MUST take up to three positional arguments.  The first two arguments,
specifying the
.SM MX
and the e-mail address to be verified, MUST be mandatory, i.e. the script
MUST exit with a status
.B "greater than 2"
if one or both are missing.  The third argument MAY optionally specify
the default timeout in seconds.  If the script does not handle an option
(i.e. an argument starting with "-"), it MUST ignore it.  It MUST exit
with a status of
.B 0
if the e-mail address could be verified positive and an exit status of
.B 1
if not. It MAY exit with a status of
.B 2
to indicate that it is not known whether the passed string
specifies a mailbox on this server.  It MUST exit with a status
.B "greater than 2"
if other errors occur.  It MAY generate arbitrary output in either
case.  It MUST NOT affect the execution of calling programs directly.
.RE

.PP
Builds
.B 2004022414
and later of the
.BR chkmadd.exp (3)
script contained in the distribution meet the argument and exit status
requirements.  (They do not meet the requirements for options yet; however,
that is a requirement for further customization of the address checks.
.BR TODO ", see below.)"

.PP        
If
.BR expect (1)
or the script described above is not available, you are required to type
SMTP commands for verification (see
.SM RFC
2821, especially the \fBVRFY\fP, \fBMAIL\fP,
.B HELO
and
.B RCPT
commands.)  Note that you SHOULD NOT use this script in a non-interactive
environment in this case.
.BR telnet (1)
may time out but the delay could interrupt that environment, and you will
receive no useful feedback anyway.  Use the
.B -a
option to prevent that.
.br
.RB ( NOTE :
It should be reconsidered whether the script is reasonable to use then.
Maybe the whole thing should be written in Expect.  That would also allow
to remove the dependency on other networking tools; however on the other
hand, it would require implementing several network protocols in Expect,
not only basic SMTP.)

.PP
From version
.B 0.1.5.2009020211
on, this script supports a
.B chkmadd
server to connect to MTAs in place of the local host.  See the
.B -s
and
.B -p
options for details.

.PP
In the next version, this script might support a
.B chkmadd
server to listen for incoming requests on any available port if the
.BR \%chkmadd.exp (1)
program can be executed on that server.  See the
.B -l
option for details.
.B (TODO)

.SH OPTIONS

.IP "\fB-a\fP, \fB--auto\fP" 
Force automatic verification via the
.BR expect (1)
\fISCRIPT\fP.  If the
.BR expect (1)
program or the
.I SCRIPT
is not available, returns with exit status
.B 2
for all addresses.
.B (TODO)

.IP "\fB-d\fP, \fB--force-dupes\fP"
Force MXs with different host name but same IP address to be asked for
\fIEMAIL_ADDRESS\fP.  This is a
.BR TODO ;
the current behavior is to ask every MX regardless of the resolved IP address.

.IP "\fB-E\fP, \fB--expect\fP \fIPROGRAM\fP"
Specify the
.BR expect (1)
.I PROGRAM
to be used.  The default is \fI/usr/bin/expect\fP.

.IP "\fB-e\fP, \fB--expect-script\fP \fISCRIPT\fP"
Specify the
.BR expect (1)
.I SCRIPT
to be used.  The default is
.br
.BR chkmadd.exp (1)
in the
.B chkmadd
program directory.

.IP "\fB-f\fP, \fB--file\fP [\fIFILE\fP]"
Read
.IR EMAIL_ADDRESS (es)
from \fIFILE\fP.  The default is the standard
input which can be equally specified as `-'.

.IP "\fB-H\fP, \fB--force-helo\fP"
Force HELO command.  RFC\ 2821 does not require a client to send HELO, and the
default is not to send it unless MAIL\ FROM fails; in fact, the RFC says that
`HELO' SHOULD NOT be required for further protocol communication.  However, some
broken/suspicious configured MTAs (like ESMTP) will terminate the connection
when receiving MAIL\ FROM or RCPT\ TO without previous HELO (this is usually
paraphrased as and sometimes even responded with "Polite people say HELO.")  
.B (TODO)

.IP "\fB-h\fP, \fB--help\fP"
Display this help screen and exit with status
.BR 127 .

.IP "\fB-l\fP, \fB--listen\fP"
Listen for parameters from stdin or on the
.I PORT
specified with
.BR -p .
Corresponds remotely with the locally given
.B -s
option.  To prevent misuse, this works together with
.B -p
only if the
.I SERVER
provides both
.BR expect (1)
and the
.BR chkmadd.exp (1)
program, i.e.
.B -a
is given implicitly.
.B (TODO)
        
.IP "\fB-p\fP, \fB--port\fP \fIPORT\fP"
Specify the port where either requests should be addressed to
.RB ( -s )
or where the
.B chkmadd
.I SERVER
should listen on
.RB ( -l ).
The default is ssh(22)/tcp unless specified otherwise in
.BR \%ssh_config (5).
.br
This option overrides the CHKMADD_PORT environment variable (see below).
Use
.RB ` "-p -" '
to make sure that the default port is used.

.IP "\fB-s\fP, \fB--server\fP \fISERVER\fP"
Specify a
.B chkmadd
\fISERVER\fP to which the request is being forwarded by the local program.
Introduced primarily to allow clients within blacklisted IP address ranges
(such as computers of \%dial-up users having dynamic IP addresses) to use servers
that are not blacklisted.  A
.B chkmadd
server is a server which can be reached via
.BR ssh (1)
and has both
.B chkmadd
and (as a security precaution)
.BR expect (1)
installed.  
.br
This option overrides the CHKMADD_SERVER environment variable (see below).
Use
.RB ` "-s -" '
to make sure that a so predefined server is NOT used.

.IP "\fB-t\fP, \fB--timeout\fP \fISECONDS\fP"
Specify the number of seconds the
.BR expect (1)
\fISCRIPT\fP should wait for a server reponse to a command before trying the
next alternative (or abort if there are no more alternatives).  The default
is
.BR 10 .
Use values greater than
.B 20
for slow connections/servers.

.IP "\fB-V\fP, \fB--version\fP"
Display version information and exit with status
.BR 127 .

.IP "\fB-v\fP, \fB--verbose\fP"
Be verbose.

.IP "\fB-y\fP, \fB--no-vrfy\fP"
Skip
.SM VRFY
command.  Some completely b0rken MTAs are already offended by VRFY before
HELO/MAIL\ FROM, and terminate the connection, or respond with an invalid
status code then.  That would confuse
.BR chkmadd.exp (1)
and return false negatives, which can be prevented by using this option.
.B (TODO)

.IP "\fIEMAIL_ADDRESS\fP"
E-mail address to be verified. May be delimited by `<' and `>'.
Separate e-mail addresses by space (\fB$IFS\fP in general).


.SH "EXIT CODES"

.TP
.B "  0"
Address verification positive or version info successfully retrieved

.TP
.B "  1"
No address

.TP
.B "  2"
Unable to verify address

.TP
.B "  3"
No address: all specified MXs are invalid

.TP
.B "127"
General error


.SH ENVIRONMENT

.TP
.B CHKMADD_PORT
Specifies the 
.I PORT
to be used by default.  If set,
.B -p
is given implicitly.

.TP
.B CHKMADD_SERVER
Specifies the
.B chkmadd
.I SERVER
to be used by default.  If set,
.B -s
is given implicitly.

.TP
.B TERM
If not `raw' and
.BR stty (1)
returns the size, use colored output with ANSI escape sequences.

.SH FILES

.TP
.I /usr/bin/expect
Default location of the
.BR expect (1)
program.
.TP
.I ./chkmadd.exp
Default location of the
.BR chkmadd.exp (1)
script.


.SH "SEE ALSO" 

.BR host (1),
.BR grep (1),
.BR telnet (1)

.PP
.SM RFC
2119 -- Key words for use in RFCs to Indicate Requirement Levels,
S. Bradner, March 1997.  <\fIhttp://www.ietf.org/rfc/rfc2119.txt\fP>

.PP
.SM RFC
2821 -- Simple Mail Transfer Protocol (\fSSMTP\fP),
J. Klensin, April 2001.  <\fIhttp://www.ietf.org/rfc/rfc2821.txt\fP>

.PP
.BR expect (1)
<\fIhttp://expect.nist.gov/\fP>,
.BR chkmadd.exp (1)

.SH BUGS
None known.  Please report bugs to <chkmadd@PointedEars.de>.


.SH NOTES
Tested with GNU/Linux 2.4.25/6/9/.30 \fB[1]\fP (Knoppix 3.4 \fB[2]\fP and
Debian 3.x \fB[3]\fP Testing/Unstable), and Cygwin 1.5.9-1 and
1.5.10(0.116/4/2) \fB[4]\fP on Microsoft Windows 2000 Professional,
Service Pack 4 \fB[5]\fP.

.PP
\fB[1]\fP <\fIhttp://kernel.org/\fP>
.br
\fB[2]\fP <\fIhttp://knopper.net/knoppix/\fP>
.br
\fB[3]\fP <\fIhttp://debian.org/\fP>
.br
\fB[4]\fP <\fIhttp://cygwin.com/\fP>
.br
\fB[5]\fP <\fIhttp://www.microsoft.com/windows2000/\fP>

.SH "LEGAL NOTICE"
Copyright (c) 2003-2006  Thomas Lahn <mehl@PointedEars.de>
.PP
This program is free software; you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by the
Free Software Foundation; either version 2 of the License, or (at your
option) any later version.
.PP
This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
(GPL) for more details.

You should have received a copy of the GNU GPL along with this program
(\fICOPYING\fP file); if not, go to [1] or write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
.PP
[1] <\fIhttp://www.gnu.org/licenses/licenses.html#GPL\fP>
.PP
.br
--
.br
Standard shell script disclaimer blurb thing:

This script is a hack.  It's brute force.  It's horrible.
It doesn't use Artificial Intelligence.  It doesn't use Virtual Reality.
It's not perl.  It's not python.  It probably won't work unchanged on
the "other" thousands of unices.  But it worksforme.  --ramiro
.br
(from \fI/usr/local/mozilla/run-mozilla.sh\fP)


.SH CREDITS
Thanks to Christoph 'Mehdorn' Weber <ich-reweb@gmx.net> for test cases
and to Don Libes <libes@nist.gov> for the great \fIexpect\fP(1) tool.


.SH AVAILABILITY
The author's latest version can be obtained from
.br
<\fIhttp://PointedEars.de/tools/network/chkmadd/\fP>.
